---
title: "Imports Arbres SE"
author: "Olivier Leroy"
date: "25 avril 2019"
output: html_document
---

# Chargement des bibliothèques 

```{r, echo=FALSE}
### manip
library(dplyr) # manip de données en tidyverse
library(tibble)
library(tidyr)
library(lubridate) # date
library(stringr) # modif sur character

### visualisation
library(ggplot2) # la visualisation
library(tmap) # carto
library(tmaptools) # + outils pour tmap
library(ggmap)# carto +
library(leaflet) # carto web
library(rsconnect) # pour partager une carte
library(RColorBrewer) # des palettes

## analyse spatiale / carto
library(sp) # classes et methodes pour données spatiales pe déclassé par SF
library(rgdal) #gdal pour projection, crud et surtout export
library(rgeos) # geos, penser à installer libgeos++-dev avant, travail avec objet sp
library(sf) # nouveau package de classes et methodes spatiales doit "remplacer" rgdal et rgeos (et ofc sp) 
library(units) # gestion des unités pour ha
library(rmapshaper) #Visvalingam’s algorithm pour ms_simplify
```

# Lecture des données 

```{r}
arbres_se.shp <- st_read("data/arbres_se_brut.geojson")
summary(arbres_se.shp)
```

EPSG : 3946
25984 point 
Toutes les infos dans DESCRIPTION qui est une chaine de caractères 

# Recodage des données

```{r}
plot(arbres_se.shp)
```


## Pour le genre

```{r}
arbres_se.shp$genus <- word(arbres_se.shp$DESCRIPTION, 1) # ici on peut prendre le premier mot et assumer le genre, genus dans OSM
head(arbres_se.shp$DESCRIPTION)
```

## pour l'espece

```{r}
unique(word(arbres_se.shp$DESCRIPTION, 2))
```

 Il semble y avoir au moins trois problèmes "x", "sp.", et "". 