---
title: "Les arbres isolés dans Open Street Map"
author: "Olivier Leroy"
date: "24 octobre 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Jeux de données

Les données sont issues d'un import d'OSM via <https://www.geofabrik.de/>. L'import c'est fait dans une BD Postgresql (10) avec les extensions postgis, postgis_topology et hstore. 

## Création de la BD

La base à d'abord été crée : en psql, et connecté en postgres (sudo -i -u postgres)
```{sql, eval = FALSE}
CREATE DATABASE [sonpetitnom];
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION hstore;
```

## import/peuplement de la BD

Puis importée via [osm2pgsql](https://wiki.openstreetmap.org/wiki/Osm2pgsql)

```{bash, , eval = FALSE}
sudo -u postgres osm2pgsql -d osmdbfrance --slim -C 8000--hstore --multi-geometry 
/home/lo82302h/Téléchargements/france-latest.osm.bz2 -W
```

-d indique la DB osmdbfrance \hfill\break
- -slim permet de sauver les données temporaires dans la DB plutot que dans la RAM \hfill\break
- -hstore indique qu'il y un type de données hstore (spécifique à postgreSQL) \hfill\break
-C indique la RAM à utilisée \hfill\break
- -multi-geometry va cr'eer des geometries multiples plutôt que de séparer en simple \hfill\break
-W demande le code ici de postgres \hfill\break

# Analyse exploratoire

## stats de base

Au moment de l'import (mi-otobre) il y avait 762167 lignes correspondant à des arbres isolés (natural=tree). Ils étaient renseignés par 27 champs (en plus de 'tags' et 'natural') completés par 146 champs dans tags. Cela fait donc rien que pour les arbres 173 champs. 


